import { icon } from './index.js';
import { escapeHTML as e, formatMessage, safeURL, tablePage, generationStates, validateDateRange } from './component-utils.js';
import { registerAI } from './hax.js';
import { registerChat } from './chat.js';
export { generationStates, formatMessage } from './component-utils.js';
let sequence = 0;
/** Explicit registration: importing this module is safe in SSR. Call in the browser. */
export function registerClarityElements() {
  if (typeof window === 'undefined' || !window.customElements) return;
  const registry = window.customElements;
  if (registry.get('cl-menu')) return;
  class Base extends HTMLElement {
    constructor() { super(); this.uid = `cl-${++sequence}`; this._data = null; }
    set data(value) { this._data = value; if(this.isConnected) this.render(); }
    get data() { return this._data; }
    connectedCallback() {
      // Honor properties assigned before custom-element registration.
      if(Object.hasOwn(this,'data')) { const value=this.data; delete this.data; this._data=value; }
      this.abort?.abort(); this.abort = new AbortController(); this.render();
      this.addEventListener('click', event => this.click?.(event), {signal:this.abort.signal});
      this.addEventListener('input', event => this.input?.(event), {signal:this.abort.signal});
      this.addEventListener('change', event => this.change?.(event), {signal:this.abort.signal});
      this.addEventListener('keydown', event => this.key?.(event), {signal:this.abort.signal});
      this.addEventListener('submit', event => { event.preventDefault(); this.submit?.(event); }, {signal:this.abort.signal});
    }
    disconnectedCallback() { this.abort?.abort(); this.cleanup?.(); }
    emit(name, detail={}) { this.dispatchEvent(new CustomEvent(`cl-${name}`, {detail,bubbles:true,composed:true})); }
    status(text) { const el=this.querySelector('[data-status]'); if(el)el.textContent=text; }
    focusAction(action) { this.querySelector(`[data-action="${action}"]`)?.focus(); }
    button(text, action, variant='secondary', extra='') { return `<button type="button" class="cl-btn cl-btn--${variant}" data-action="${action}" ${extra}>${text}</button>`; }
    render() {}
  }
  const define=(name,klass)=>registry.define(name,klass);
  define('cl-menu', class extends Base {
    render() {
      const items=this.data?.items || [{id:'rename',label:'Rename'},{id:'duplicate',label:'Duplicate'},{id:'archive',label:'Archive'}];
      this.innerHTML=`${this.button(e(this.getAttribute('label') || 'Project actions')+' '+icon('chevron',{size:12}),'open','secondary',`aria-haspopup="menu" aria-expanded="false" aria-controls="${this.uid}-menu"`)}<div class="cl-floating" id="${this.uid}-menu" popover role="menu" aria-label="${e(this.getAttribute('label') || 'Project actions')}">${items.map(item=>`<button class="cl-menu-item" role="menuitem" tabindex="-1" data-value="${e(item.id)}" ${item.disabled?'disabled':''}>${e(item.label)}</button>`).join('')}</div><span class="cl-sr-only" data-status role="status"></span>`;
      const pop=this.querySelector('[popover]');pop.addEventListener('toggle',()=>{this.querySelector('[data-action="open"]').setAttribute('aria-expanded',String(pop.matches(':popover-open')));});
    }
    open(last=false) { const pop=this.querySelector('[popover]');pop.showPopover();this.querySelector('[data-action="open"]').setAttribute('aria-expanded','true'); const rect=this.getBoundingClientRect();pop.style.left=`${Math.max(8,Math.min(rect.left,innerWidth-pop.offsetWidth-8))}px`;pop.style.top=`${Math.max(8,Math.min(rect.bottom+6,innerHeight-pop.offsetHeight-8))}px`;const items=this.querySelectorAll('[role="menuitem"]:not(:disabled)');items[last?items.length-1:0]?.focus(); }
    click(event) { const item=event.target.closest('[data-value]');if(item){this.querySelector('[popover]').hidePopover();this.querySelector('[data-action="open"]').setAttribute('aria-expanded','false');this.focusAction('open');this.status(`${item.textContent} selected`);this.emit('menu-select',{value:item.dataset.value});}else if(event.target.closest('[data-action="open"]')){const pop=this.querySelector('[popover]');pop.matches(':popover-open')?pop.hidePopover():this.open();} }
    key(event) { const pop=this.querySelector('[popover]');if(event.key==='Escape'){pop.hidePopover();this.querySelector('[data-action="open"]').setAttribute('aria-expanded','false');this.focusAction('open');return;}if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();if(!pop.matches(':popover-open')){this.open(event.key==='ArrowUp');return;}const items=[...this.querySelectorAll('[role="menuitem"]:not(:disabled)')];const i=items.indexOf(document.activeElement);items[event.key==='Home'?0:event.key==='End'?items.length-1:(i+(event.key==='ArrowUp'?-1:1)+items.length)%items.length]?.focus();} }
  });
  define('cl-popover', class extends Base {
    render(){this.innerHTML=`${this.button(e(this.getAttribute('label')||'About this setting'),'open','secondary',`popovertarget="${this.uid}-panel"`)}<div class="cl-floating cl-popover-panel" id="${this.uid}-panel" popover><h3>${e(this.data?.title||'Workspace visibility')}</h3><p>${e(this.data?.text||'Only invited people can access this workspace. You can change visibility in settings.')}</p>${this.button('Got it','close','secondary',`popovertarget="${this.uid}-panel" popovertargetaction="hide"`)}</div>`;}
  });
  define('cl-tooltip',class extends Base {
    render(){this.innerHTML=`<span class="cl-tooltip-wrap"><button type="button" class="cl-icon-btn" aria-label="${e(this.getAttribute('label')||'More information')}" aria-describedby="${this.uid}-tip">${icon('book')}</button><span class="cl-tooltip" role="tooltip" id="${this.uid}-tip">${e(this.getAttribute('text')||'Only invited people can see this project.')}</span></span>`;}
    key(event){if(event.key==='Escape'){this.querySelector('[role="tooltip"]').hidden=true;}}
    connectedCallback(){super.connectedCallback();for(const type of ['focusin','pointerenter'])this.addEventListener(type,()=>{this.querySelector('[role="tooltip"]').hidden=false;},{signal:this.abort.signal});}
  });
  define('cl-combobox',class extends Base {
    render(){this.options=this.data?.options||['Design','Engineering','Research','Product','Operations'];this.value=this.value||'';this.innerHTML=`<label class="cl-field" for="${this.uid}-input">${e(this.getAttribute('label')||'Team')}<input class="cl-input" id="${this.uid}-input" role="combobox" autocomplete="off" aria-autocomplete="list" aria-expanded="false" aria-controls="${this.uid}-list" value="${e(this.value)}" placeholder="Search and select a team"></label><ul class="cl-options" role="listbox" aria-label="Available teams" id="${this.uid}-list" hidden></ul><span class="cl-help" data-status role="status"></span>`;this.active=-1;}
    connectedCallback(){super.connectedCallback();this.addEventListener('focusout',event=>{if(!this.contains(event.relatedTarget))this.close(true);},{signal:this.abort.signal});this.addEventListener('pointerdown',event=>{if(event.target.closest('[role="option"]'))event.preventDefault();},{signal:this.abort.signal});}
    show(query=''){this.matches=this.options.filter(v=>v.toLowerCase().includes(query.toLowerCase()));const list=this.querySelector('ul');list.hidden=false;list.innerHTML=this.matches.map((v,i)=>`<li id="${this.uid}-option-${i}" role="option" aria-selected="${v===this.value}" data-index="${i}">${e(v)}</li>`).join('')||'<li class="cl-help">No matching options</li>';this.active=-1;const input=this.querySelector('input');input.setAttribute('aria-expanded','true');input.removeAttribute('aria-activedescendant');this.status(`${this.matches.length} options available`);}
    close(restore=false){this.querySelector('ul').hidden=true;const input=this.querySelector('input');input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');if(restore)input.value=this.value;}
    select(i){if(!this.matches?.[i])return;this.value=this.matches[i];this.querySelector('input').value=this.value;this.close();this.status(`${this.value} selected`);this.emit('change',{value:this.value});}
    input(event){this.show(event.target.value);}
    click(event){const option=event.target.closest('[data-index]');if(option)this.select(Number(option.dataset.index));else if(event.target.matches('input'))this.show(event.target.value);}
    key(event){if(event.key==='Escape'){this.close(true);return;}if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();if(this.querySelector('ul').hidden)this.show();if(!this.matches.length)return;this.active=event.key==='Home'?0:event.key==='End'?this.matches.length-1:(this.active+(event.key==='ArrowUp'?-1:1)+this.matches.length)%this.matches.length;const id=`${this.uid}-option-${this.active}`;this.querySelector('input').setAttribute('aria-activedescendant',id);this.querySelectorAll('[role="option"]').forEach((el,i)=>el.dataset.active=String(i===this.active));document.getElementById(id)?.scrollIntoView({block:'nearest'});}if(event.key==='Enter'&&!this.querySelector('ul').hidden){event.preventDefault();this.select(this.active);}}
  });
  define('cl-multiselect',class extends Base {
    render(){this.options=this.data?.options||['Research','Design','Finance','Operations'];this.selected ||= new Set();this.innerHTML=`<fieldset class="cl-fieldset"><legend>${e(this.getAttribute('label')||'Project categories')}</legend><input class="cl-input" type="search" placeholder="Filter categories" aria-label="Filter categories"><div class="cl-choice-list">${this.options.map(v=>`<label class="cl-check" data-option="${e(v)}"><input type="checkbox" value="${e(v)}" ${this.selected.has(v)?'checked':''}>${e(v)}</label>`).join('')}</div><div class="cl-row" data-chips></div><p class="cl-help" data-status role="status"></p></fieldset>`;this.chips();}
    chips(){this.querySelector('[data-chips]').innerHTML=[...this.selected].map(v=>`<button type="button" class="cl-chip" data-remove="${e(v)}" aria-label="Remove ${e(v)}">${e(v)} ${icon('close',{size:12})}</button>`).join('');this.status(`${this.selected.size} selected`);}
    input(event){if(event.target.type==='search')this.querySelectorAll('[data-option]').forEach(el=>el.hidden=!el.dataset.option.toLowerCase().includes(event.target.value.toLowerCase()));}
    change(event){if(event.target.type==='checkbox'){event.target.checked?this.selected.add(event.target.value):this.selected.delete(event.target.value);this.chips();this.emit('change',{values:[...this.selected]});}}
    click(event){const b=event.target.closest('[data-remove]');if(b){this.selected.delete(b.dataset.remove);this.querySelectorAll('input[type="checkbox"]').forEach(el=>el.checked=this.selected.has(el.value));this.chips();this.querySelector('input[type="search"]').focus();this.emit('change',{values:[...this.selected]});}}
  });
  define('cl-date-range',class extends Base {
    render(){this.innerHTML=`<fieldset class="cl-fieldset"><legend>${e(this.getAttribute('label')||'Reporting period')}</legend><div class="cl-grid"><label class="cl-field">Start date<input class="cl-input" type="date" data-start aria-describedby="${this.uid}-error" value="${e(this.data?.start||'')}"></label><label class="cl-field">End date<input class="cl-input" type="date" data-end aria-describedby="${this.uid}-error" value="${e(this.data?.end||'')}"></label></div><p class="cl-error" role="status" id="${this.uid}-error" data-status></p></fieldset>`;}
    change(){const start=this.querySelector('[data-start]').value,end=this.querySelector('[data-end]').value;const valid=validateDateRange(start,end);this.querySelector('[data-end]').setCustomValidity(valid?'':'End date must be on or after start date.');this.querySelector('[data-end]').setAttribute('aria-invalid',String(!valid));this.status(valid?'':'End date must be on or after start date.');this.emit('change',{start,end,valid});}
  });
  define('cl-drawer',class extends Base {
    render(){this.innerHTML=`${this.button(e(this.getAttribute('label')||'Open details'),'open')}<dialog class="cl-dialog cl-drawer-panel" aria-labelledby="${this.uid}-title"><form method="dialog"><div class="cl-split"><h2 id="${this.uid}-title">${e(this.data?.title||'Project details')}</h2><button class="cl-icon-btn" aria-label="Close details" formnovalidate>${icon('close')}</button></div><p class="cl-muted">${e(this.data?.text||'Keep the surrounding workspace in view while inspecting this project.')}</p><label class="cl-field cl-spaced">Project name<input class="cl-input" name="name" required value="${e(this.data?.name||'Research workspace')}"></label><div class="cl-dialog__actions"><button class="cl-btn cl-btn--secondary" value="cancel" formnovalidate>Cancel</button><button class="cl-btn cl-btn--primary" value="save">Save details</button></div></form></dialog><p class="cl-help" data-status role="status"></p>`;}
    click(event){if(event.target.closest('[data-action="open"]'))this.querySelector('dialog').showModal();}
    submit(event){const save=event.submitter?.value==='save';if(save){const value=this.querySelector('input').value;this.emit('save',{name:value});this.status('Details updated in this example.');}this.querySelector('dialog').close(save?'save':'cancel');}
  });
  define('cl-upload',class extends Base {
    render(){this.files ||= [];this.innerHTML=`<div class="cl-dropzone"><span class="cl-icon-tile">${icon('download')}</span><label class="cl-field">${e(this.getAttribute('label')||'Attach files')}<input type="file" multiple ${this.getAttribute('accept')?`accept="${e(this.getAttribute('accept'))}"`:''}></label><p class="cl-help">Choose files or drop them here. Files stay local until your application uploads them.</p></div><ul class="cl-file-list"></ul><p class="cl-help" role="status" data-status></p>`;this.list();}
    connectedCallback(){super.connectedCallback();this.addEventListener('dragover',event=>{event.preventDefault();},{signal:this.abort.signal});this.addEventListener('drop',event=>{event.preventDefault();this.addFiles([...event.dataTransfer.files]);},{signal:this.abort.signal});}
    addFiles(files){const max=Number(this.getAttribute('max-size')||10485760);const accepted=[],errors=[];for(const file of files){if(file.size>max){errors.push(`${file.name} exceeds ${Math.round(max/1048576)} MB.`);continue;}const accept=(this.getAttribute('accept')||'').split(',').map(v=>v.trim()).filter(Boolean);if(accept.length&&!accept.some(v=>v.startsWith('.')?file.name.toLowerCase().endsWith(v.toLowerCase()):v.endsWith('/*')?file.type.startsWith(v.slice(0,-1)):file.type===v)){errors.push(`${file.name} has an unsupported file type.`);continue;}accepted.push(file);}this.files.push(...accepted);this.list();this.status(errors.join(' ')||`${accepted.length} files added. Ready for your application.`);this.emit('files',{files:[...this.files],errors});}
    list(){this.querySelector('ul').innerHTML=this.files.map((f,i)=>`<li><span>${e(f.name)} <small>${Math.ceil(f.size/1024)} KB · Local</small></span>${this.button('Remove',`remove-${i}`,'ghost',`aria-label="Remove ${e(f.name)}"`)}</li>`).join('');}
    change(event){if(event.target.type==='file'){this.addFiles([...event.target.files]);event.target.value='';}}
    click(event){const action=event.target.closest('[data-action]')?.dataset.action;if(action?.startsWith('remove-')){this.files.splice(Number(action.slice(7)),1);this.list();this.querySelector('input').focus();this.emit('files',{files:[...this.files],errors:[]});}}
  });
  define('cl-data-table',class extends Base {
    render(){this.rows=this.data?.rows||[];this.columns=this.data?.columns||[{key:'name',label:'Project'},{key:'owner',label:'Owner'},{key:'status',label:'Status'}];this.state ||= {query:'',sort:this.columns[0]?.key||'name',direction:'asc',page:1,size:5};this.selected ||= new Set();this.innerHTML=`<div class="cl-table-toolbar"><label class="cl-search">${icon('search',{size:14})}<input type="search" aria-label="Filter table" placeholder="Filter records…" value="${e(this.state.query)}"></label>${this.button('Clear filters','clear','ghost')}</div><div class="cl-row" data-filter-chip></div><div class="cl-table-wrap" data-table></div><div class="cl-pagination" aria-label="Pagination">${this.button('Previous','previous')}<span data-page role="status"></span>${this.button('Next','next')}</div><div class="cl-row"><span class="cl-help" data-selection role="status"></span>${this.button('Clear selection','unselect','ghost')}${this.button('Use selected','bulk','secondary')}</div>`;this.paint();}
    paint(){this.result=tablePage(this.rows,this.state);this.state.page=this.result.page;this.querySelector('[data-table]').innerHTML=`<table class="cl-table"><caption class="cl-sr-only">${e(this.getAttribute('label')||'Projects')}</caption><thead><tr><th scope="col"><input type="checkbox" data-all aria-label="Select current page" ${this.result.rows.length&&this.result.rows.every(r=>this.selected.has(r.id))?'checked':''}></th>${this.columns.map(c=>`<th scope="col" aria-sort="${this.state.sort===c.key?(this.state.direction==='asc'?'ascending':'descending'):'none'}"><button class="cl-sort" data-sort="${e(c.key)}">${e(c.label)} ${this.state.sort===c.key?(this.state.direction==='asc'?'↑':'↓'):''}</button></th>`).join('')}</tr></thead><tbody>${this.result.rows.map(r=>`<tr><td><input type="checkbox" data-id="${e(r.id)}" aria-label="Select ${e(r.name||r.id)}" ${this.selected.has(r.id)?'checked':''}></td>${this.columns.map(c=>`<td>${e(r[c.key])}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${this.columns.length+1}">No matching records. Clear filters to start again.</td></tr>`}</tbody></table>`;const count=this.result.rows.filter(r=>this.selected.has(r.id)).length;this.querySelector('[data-all]').indeterminate=count>0&&count<this.result.rows.length;this.querySelector('[data-page]').textContent=`Page ${this.result.page} of ${this.result.pages} · ${this.result.total} records`;this.querySelector('[data-action="previous"]').disabled=this.result.page===1;this.querySelector('[data-action="next"]').disabled=this.result.page===this.result.pages;this.querySelector('[data-selection]').textContent=`${this.selected.size} selected across pages`;this.querySelector('[data-action="bulk"]').disabled=!this.selected.size;this.querySelector('[data-filter-chip]').innerHTML=this.state.query?`<button class="cl-chip" data-action="clear" type="button">Filter: ${e(this.state.query)} ×</button>`:'';}
    input(event){if(event.target.type==='search'){this.state.query=event.target.value;this.state.page=1;this.paint();}}
    change(event){if(event.target.hasAttribute('data-all'))this.result.rows.forEach(r=>event.target.checked?this.selected.add(r.id):this.selected.delete(r.id));else if(event.target.hasAttribute('data-id')){const id=this.rows.find(r=>String(r.id)===event.target.dataset.id)?.id;event.target.checked?this.selected.add(id):this.selected.delete(id);}else return;const selectedId=event.target.dataset.id;const wasAll=event.target.hasAttribute('data-all');this.paint();if(wasAll)this.querySelector('[data-all]').focus();else [...this.querySelectorAll('[data-id]')].find(el=>el.dataset.id===selectedId)?.focus();this.emit('selection',{ids:[...this.selected]});}
    click(event){const b=event.target.closest('button');if(!b)return;if(b.dataset.sort){this.state.direction=this.state.sort===b.dataset.sort&&this.state.direction==='asc'?'desc':'asc';this.state.sort=b.dataset.sort;this.paint();this.querySelectorAll('[data-sort]').forEach(el=>{if(el.dataset.sort===b.dataset.sort)el.focus();});return;}switch(b.dataset.action){case'previous':this.state.page--;break;case'next':this.state.page++;break;case'clear':this.state.query='';this.state.page=1;this.querySelector('input[type="search"]').value='';this.querySelector('input[type="search"]').focus();break;case'unselect':this.selected.clear();this.emit('selection',{ids:[]});break;case'bulk':this.emit('bulk-action',{ids:[...this.selected]});return;default:return;}this.paint();}
  });
  define('cl-stepper',class extends Base {
    render(){this.step ||= 0;this.values ||= {};this.steps=this.data?.steps||[{title:'Name',name:'name',label:'Workspace name'},{title:'Owner',name:'owner',label:'Workspace owner'},{title:'Review'}];this.innerHTML=`<ol class="cl-steps">${this.steps.map((s,i)=>`<li ${i===this.step?'aria-current="step"':''}><span>${i+1}</span>${e(s.title)}</li>`).join('')}</ol><form><div data-step-body></div><div class="cl-row cl-spaced">${this.button('Back','back','secondary',this.step===0?'disabled':'')}<button class="cl-btn cl-btn--primary" type="submit">${this.step===this.steps.length-1?'Finish':'Continue'}</button></div></form><p class="cl-help" data-status role="status"></p>`;const s=this.steps[this.step];this.querySelector('[data-step-body]').innerHTML=s.name?`<label class="cl-field">${e(s.label)}<input class="cl-input" name="${e(s.name)}" required value="${e(this.values[s.name]||'')}"></label>`:`<h3>Review your details</h3><dl class="cl-definition">${Object.entries(this.values).map(([k,v])=>`<dt>${e(k)}</dt><dd>${e(v)}</dd>`).join('')}</dl>`;}
    submit(){const input=this.querySelector('input');if(input)this.values[input.name]=input.value;if(this.step<this.steps.length-1){this.step++;this.render();this.querySelector('input,button[type="submit"]').focus();}else{this.status('Setup details submitted.');this.emit('complete',{values:{...this.values}});}}
    click(event){if(event.target.closest('[data-action="back"]')&&this.step>0){const input=this.querySelector('input');if(input)this.values[input.name]=input.value;this.step--;this.render();this.querySelector('input,button[type="submit"]').focus();}}
  });
  registerAI({Base,define,e,icon,safeURL,generationStates});
  registerChat({Base,define,e,icon,safeURL,generationStates,formatMessage});
}
