/** HAX-inspired patterns. UI events do not execute actions, upload files, or train models. */
export function registerAI({Base,define,e,icon,safeURL,generationStates}) {
  const heading=(title,tag='AI assistance')=>`<div class="cl-split"><h3>${e(title)}</h3><span class="cl-badge cl-badge--purple">${icon('sparkles',{size:12})}${e(tag)}</span></div>`;
  const status='<p class="cl-help cl-spaced" role="status" data-status></p>';
  define('cl-ai-capability',class extends Base {
    render(){const d=this.data||{};this.innerHTML=`<section class="cl-ai-panel cl-stack">${heading(d.title||'A research partner, with limits')}<p>${e(d.description||'Summarize selected documents and suggest follow-up questions.')}</p><div class="cl-ai-columns"><div><h4>Can help with</h4><ul>${(d.capabilities||['Summaries of provided material','Drafts you can edit and review']).map(v=>`<li>${e(v)}</li>`).join('')}</ul></div><div><h4>Keep in mind</h4><ul>${(d.limitations||['May omit details or misinterpret a source','Does not verify facts outside the selected material']).map(v=>`<li>${e(v)}</li>`).join('')}</ul></div></div><p class="cl-help">${e(d.quality||'Review source material before relying on a result. No measured accuracy is available in this demonstration.')}</p><div class="cl-row">${(d.examples||['Summarize the key changes','Identify missing information']).map((v,i)=>this.button(e(v),`example-${i}`)).join('')}</div></section>`;}
    click(event){const action=event.target.closest('[data-action]')?.dataset.action;if(action?.startsWith('example-'))this.emit('invoke',{prompt:(this.data?.examples||['Summarize the key changes','Identify missing information'])[Number(action.slice(8))]});}
  });
  define('cl-ai-suggestion',class extends Base {
    render(){this.state ||= 'review';this.value ??= this.data?.text||'Add a source review before publishing the summary.';this.innerHTML=`<section class="cl-ai-panel cl-stack">${heading(this.data?.title||'Suggested next step',this.state==='review'?'Needs review':this.state)}${this.state==='editing'?`<label class="cl-field">Edit suggestion<textarea class="cl-textarea">${e(this.value)}</textarea></label>`:`<p>${e(this.value)}</p>`}<p class="cl-help">${e(this.data?.context||'Suggested because this draft contains claims that need supporting evidence.')}</p><div class="cl-row">${this.state==='review'?this.button('Accept','accept','primary')+this.button('Edit','edit')+this.button('Dismiss','dismiss','ghost'):this.state==='editing'?this.button('Save edit','save','primary')+this.button('Cancel','cancel'):this.button('Undo','undo')}</div>${status}</section>`;}
    click(event){const action=event.target.closest('[data-action]')?.dataset.action;if(!action)return;if(action==='edit')this.state='editing';if(action==='save'){this.value=this.querySelector('textarea').value;this.state='review';this.emit('suggestion',{action:'edit',text:this.value});}if(action==='cancel'||action==='undo')this.state='review';if(action==='accept'||action==='dismiss'){this.state=action==='accept'?'accepted':'dismissed';this.emit('suggestion',{action,text:this.value});}if(action==='undo')this.emit('suggestion',{action:'undo',text:this.value});this.render();this.querySelector('textarea,button')?.focus();}
  });
  define('cl-ai-clarification',class extends Base {
    render(){const d=this.data||{};this.innerHTML=`<form class="cl-ai-panel cl-stack">${heading(d.title||'Which period should I compare?','Needs clarification')}<p>${e(d.reason||'The request mentions “last quarter,” but does not specify a calendar or financial quarter.')}</p><fieldset class="cl-fieldset"><legend>Choose an interpretation</legend>${(d.options||['Last calendar quarter','Last financial quarter']).map(v=>`<label class="cl-check"><input type="radio" name="interpretation" value="${e(v)}">${e(v)}</label>`).join('')}<label class="cl-field">Or clarify in your own words<input class="cl-input" name="custom" placeholder="e.g. January through March"></label></fieldset><div class="cl-row"><button class="cl-btn cl-btn--primary" type="submit">Continue with clarification</button>${this.button('Skip assistance','skip','ghost')}</div>${status}</form>`;}
    submit(){const answer=this.querySelector('[name="custom"]').value.trim()||this.querySelector(':checked')?.value;if(!answer){this.status('Choose an option or enter a clarification.');this.querySelector('input').focus();return;}this.status(`Using: ${answer}`);this.emit('clarify',{answer});}
    click(event){if(event.target.closest('[data-action="skip"]')){this.status('Assistance skipped. You can continue manually.');this.emit('dismiss');}}
  });
  define('cl-ai-evidence',class extends Base {
    render(){const d=this.data||{};this.innerHTML=`<section class="cl-ai-panel cl-stack">${heading(d.title||'Why this suggestion?','Evidence')}<p>${e(d.summary||'The draft mentions an outcome without a supporting source. A review step gives you a chance to verify it.')}</p><details class="cl-disclosure"><summary>Inputs and assumptions</summary><ul>${(d.inputs||['Only the selected documents were considered.','Assumption: this draft is intended for publication.']).map(v=>`<li>${e(v)}</li>`).join('')}</ul></details><ul class="cl-source-list">${(d.sources||[]).map((s,i)=>{const url=safeURL(s.url||'');return `<li><span class="cl-source-number">${i+1}</span><div><strong>${url&&s.state!=='unavailable'?`<a href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(s.title)}</a>`:e(s.title)}</strong><p>${e(s.excerpt||'No excerpt available.')}</p><span class="cl-badge ${s.state==='conflicting'?'cl-badge--warning':''}">${e(s.state||'Provided source')}</span>${s.date?` <small>${e(s.date)}</small>`:''}${s.state==='unavailable'?'<p class="cl-help">Source unavailable. Verify this claim elsewhere before using it.</p>':''}</div></li>`;}).join('')||'<li>No sources were supplied. This result is not source-verified.</li>'}</ul><p class="cl-help">Explanations summarize relevant inputs and evidence; they are not private model reasoning or proof of correctness.</p></section>`;}
  });
  define('cl-ai-correction',class extends Base {
    render(){const d=this.data||{};this.original ??= d.original||'The team will finish the review on Friday.';this.value ??= d.proposed||'The team expects to finish the review on Friday, pending source verification.';this.innerHTML=`<section class="cl-ai-panel cl-stack">${heading(d.title||'Review the proposed wording','Editable draft')}<div class="cl-ai-columns"><div class="cl-diff-before"><h4>Original</h4><p>${e(this.original)}</p></div><label class="cl-field cl-diff-after">Proposed revision<textarea class="cl-textarea">${e(this.value)}</textarea></label></div><div class="cl-row">${this.button('Apply revision','apply','primary')}${this.button('Restore original','restore')}${this.button('Undo last change','undo','ghost',this.previous===undefined?'disabled':'')}</div>${status}</section>`;}
    click(event){const action=event.target.closest('[data-action]')?.dataset.action;if(!action)return;const current=this.querySelector('textarea').value;if(action==='undo'){if(this.previous===undefined)return;this.value=this.previous;this.previous=undefined;}else{this.previous=action==='restore'?current:this.value;this.value=action==='restore'?this.original:current;}this.render();this.status(action==='apply'?'Revision submitted to your application.':action==='restore'?'Original restored in the editor.':'Previous text restored.');this.focusAction('apply');this.emit('correction',{action,text:this.value});}
  });
  define('cl-ai-feedback',class extends Base {
    render(){this.innerHTML=`<form class="cl-ai-panel cl-stack">${heading(this.data?.title||'Feedback on this claim','Feedback')}<p>${e(this.data?.claim||'The summary includes all material changes.')}</p><fieldset class="cl-fieldset"><legend>What should be improved?</legend>${['Incorrect claim','Missing context','Irrelevant suggestion','Biased or inappropriate language'].map(v=>`<label class="cl-check"><input type="checkbox" name="reason" value="${e(v)}">${e(v)}</label>`).join('')}</fieldset><label class="cl-field">Additional detail <span class="cl-help">Optional</span><textarea class="cl-textarea" name="detail" placeholder="Point to the part that needs attention"></textarea></label><p class="cl-help">${e(this.data?.consequence||'This demo emits feedback to the page only. It does not save feedback or train a model.')}</p><div><button class="cl-btn cl-btn--primary" type="submit">Submit feedback</button></div>${status}</form>`;}
    submit(){const reasons=[...this.querySelectorAll(':checked')].map(el=>el.value),detail=this.querySelector('textarea').value.trim();if(!reasons.length&&!detail){this.status('Choose a reason or add a detail.');return;}this.emit('feedback',{claimId:this.data?.claimId||null,reasons,detail});this.status('Feedback submitted to the application handler.');}
  });
  define('cl-ai-context',class extends Base {
    render(){this.items ??= [...(this.data?.items||[{id:'brief',label:'Project brief',detail:'Selected document · this session'},{id:'request',label:'Compare the latest changes',detail:'Your previous request · this session'}])];this.innerHTML=`<section class="cl-ai-panel cl-stack">${heading('Context used for this request','This session')}<p class="cl-help">Review what is included. Removing an item requests its exclusion from subsequent calls; the application must enforce that change.</p><ul class="cl-context-list">${this.items.map(item=>`<li><div><strong>${e(item.label)}</strong><small>${e(item.detail)}</small></div><div class="cl-row">${this.button('Reference',`reference-${item.id}`,'ghost')}${this.button('Remove',`remove-${item.id}`,'ghost')}</div></li>`).join('')||'<li>No context selected. Add context in your application before requesting a grounded answer.</li>'}</ul><div>${this.button('Clear context','clear','secondary',!this.items.length?'disabled':'')}</div>${status}</section>`;}
    click(event){const action=event.target.closest('[data-action]')?.dataset.action;if(!action)return;if(action.startsWith('reference-')){this.emit('reference',{id:action.slice(10)});this.status('Context reference requested.');return;}if(action==='clear')this.items=[];else if(action.startsWith('remove-'))this.items=this.items.filter(i=>i.id!==action.slice(7));else return;this.render();this.querySelector('button:not(:disabled)')?.focus();this.emit('context-change',{items:[...this.items]});}
  });
  define('cl-ai-preferences',class extends Base {
    render(){const d=this.data||{};this.innerHTML=`<form class="cl-ai-panel cl-stack">${heading('Choose how AI helps','Preferences')}<label class="cl-switch"><input type="checkbox" role="switch" name="assistance" ${d.assistance===false?'':'checked'}><span class="cl-switch-track" aria-hidden="true"></span>Enable AI assistance</label><label class="cl-switch"><input type="checkbox" role="switch" name="personalize" ${d.personalize?'checked':''}><span class="cl-switch-track" aria-hidden="true"></span>Use feedback to personalize suggestions</label><fieldset class="cl-fieldset"><legend>Context access</legend><label class="cl-check"><input type="radio" name="scope" value="selected" ${d.scope!=='workspace'?'checked':''}>Only documents I select</label><label class="cl-check"><input type="radio" name="scope" value="workspace" ${d.scope==='workspace'?'checked':''}>Documents in this workspace</label></fieldset><p class="cl-help">Changes apply when your application saves and enforces them. This component grants no access by itself.</p><div><button type="submit" class="cl-btn cl-btn--primary">Save preferences</button></div>${status}</form>`;}
    submit(){this.emit('preferences',{assistance:this.querySelector('[name="assistance"]').checked,personalize:this.querySelector('[name="personalize"]').checked,scope:this.querySelector('[name="scope"]:checked').value});this.status('Preferences submitted. Your application controls persistence and access.');}
  });
  define('cl-ai-change-notice',class extends Base {
    render(){this.innerHTML=`<section class="cl-ai-panel cl-stack">${heading(this.data?.title||'Source references are now available','What changed')}<p>${e(this.data?.description||'New summaries can link claims to selected source material. Existing drafts and your preferences are unchanged.')}</p><details class="cl-disclosure"><summary>What this means for you</summary><p>${e(this.data?.impact||'You can inspect references before accepting a suggestion. A reference does not guarantee that a claim is correct.')}</p></details><div>${this.button('Acknowledge','acknowledge','primary')}</div>${status}</section>`;}
    click(event){if(event.target.closest('[data-action="acknowledge"]')){this.status('Change acknowledged.');event.target.closest('button').disabled=true;this.emit('acknowledge',{id:this.data?.id||null});}}
  });
  define('cl-ai-composer',class extends Base {
    render(){this.context ??= [...(this.data?.context||['Project brief','Current draft'])];this.innerHTML=`<form class="cl-ai-panel cl-stack">${heading('What would you like help with?','Prompt')}<label class="cl-field" for="${this.uid}-prompt">Your request<textarea id="${this.uid}-prompt" class="cl-textarea" required maxlength="4000" placeholder="Ask a question about the selected context…"></textarea></label><div class="cl-row">${(this.data?.suggestions||['Summarize the key changes','Find gaps in the evidence']).map((v,i)=>this.button(e(v),`prompt-${i}`,'ghost')).join('')}</div><fieldset class="cl-fieldset"><legend>Include context</legend>${this.context.map(v=>`<label class="cl-check"><input type="checkbox" name="context" value="${e(v)}" checked>${e(v)}</label>`).join('')||'<p class="cl-help">No context supplied.</p>'}</fieldset><label class="cl-field">Attachments<input type="file" multiple name="files"><span class="cl-help">Files stay local until your application handles this request.</span></label><div class="cl-split"><span class="cl-help" data-count>0 / 4000</span><button class="cl-btn cl-btn--primary" type="submit">Send request ${icon('arrow',{size:14})}</button></div>${status}</form>`;}
    input(event){if(event.target.matches('textarea'))this.querySelector('[data-count]').textContent=`${event.target.value.length} / 4000`;}
    click(event){const a=event.target.closest('[data-action]')?.dataset.action;if(a?.startsWith('prompt-')){const field=this.querySelector('textarea');field.value=(this.data?.suggestions||['Summarize the key changes','Find gaps in the evidence'])[Number(a.slice(7))];this.input({target:field});field.focus();}}
    submit(){const prompt=this.querySelector('textarea').value.trim();if(!prompt){this.status('Enter a request before sending.');return;}this.emit('request',{prompt,context:[...this.querySelectorAll('[name="context"]:checked')].map(el=>el.value),files:[...this.querySelector('[type="file"]').files]});this.status('Request handed to the application. No model is connected in this example.');}
  });
  define('cl-ai-generation',class extends Base {
    render(){const d=this.data||{};const state=generationStates.includes(d.state)?d.state:'idle';const labels={idle:'Ready when you are',waiting:'Waiting for the service',generating:'Generating a draft',complete:'Draft ready for review',interrupted:'Generation stopped',incomplete:'Only part of the result is available',failed:'The request failed'};this.innerHTML=`<section class="cl-ai-panel cl-stack" aria-busy="${['waiting','generating'].includes(state)}">${heading('Generation status',state)}<p role="status">${['waiting','generating'].includes(state)?'<span class="cl-spinner" aria-hidden="true"></span> ':''}${labels[state]}</p>${d.text?`<div class="cl-output" tabindex="0" aria-label="Generated output">${e(d.text)}</div>`:''}${d.error?`<p class="cl-error">${e(d.error)}</p>`:''}<div class="cl-row">${['waiting','generating'].includes(state)?this.button('Stop generation','stop'):['failed','interrupted','incomplete'].includes(state)?this.button('Retry request','retry','primary'):''}</div><p class="cl-help">${e(d.note||'The application supplies real status and output. Stop and retry emit requests to its controller.')}</p>${status}</section>`;}
    click(event){const action=event.target.closest('[data-action]')?.dataset.action;if(action==='stop'||action==='retry'){this.emit(action);this.status(`${action==='stop'?'Stop':'Retry'} requested; waiting for the application.`);}}
  });
  define('cl-ai-action-review',class extends Base {
    render(){const d=this.data||{};this.state ||= 'pending';this.actions=d.actions||[{id:'draft',label:'Save the summary as a draft',detail:'Creates a draft in the selected workspace.'},{id:'notify',label:'Notify the review team',detail:'Sends the draft title to workspace reviewers.'}];this.innerHTML=`<section class="cl-ai-panel cl-stack">${heading(d.title||'Review before taking action',this.state)}<p>${e(d.description||'Choose which proposed actions to authorize. Nothing runs until your application handles approval.')}</p><fieldset class="cl-fieldset" ${this.state!=='pending'?'disabled':''}><legend>Proposed scope</legend>${this.actions.map(a=>`<label class="cl-check cl-action-choice"><input type="checkbox" value="${e(a.id)}" checked><span><strong>${e(a.label)}</strong><small>${e(a.detail)}</small></span></label>`).join('')}</fieldset><p class="cl-help">${e(d.consequence||'Review the selected scope. An approval is authorization, not confirmation that execution succeeded.')}</p><div class="cl-row">${this.state==='pending'?this.button('Approve selected','approve','primary')+this.button('Reject proposal','reject','secondary'):this.button('Review again','reset')}</div>${status}</section>`;}
    click(event){const action=event.target.closest('[data-action]')?.dataset.action;if(action==='reset'){this.state='pending';this.render();this.focusAction('approve');return;}if(!['approve','reject'].includes(action)||this.state!=='pending')return;const ids=[...this.querySelectorAll(':checked')].map(el=>el.value);if(action==='approve'&&!ids.length){this.status('Select at least one action or reject the proposal.');return;}this.state=action==='approve'?'approved':'rejected';this.emit('decision',{decision:action,ids:action==='approve'?ids:[]});this.render();this.status(action==='approve'?'Approval emitted. Execution has not been confirmed.':'Proposal rejected.');this.focusAction('reset');}
  });
  define('cl-ai-execution',class extends Base {
    render(){const d=this.data||{};this.innerHTML=`<section class="cl-ai-panel cl-stack">${heading(d.title||'Execution activity','Application status')}<ol class="cl-execution-list">${(d.steps||[]).map(s=>`<li><span class="cl-badge ${s.state==='failed'?'cl-badge--danger':s.state==='complete'?'cl-badge--success':'cl-badge--info'}">${e(s.state||'pending')}</span><div><strong>${e(s.label)}</strong><p>${e(s.detail||'')}</p>${s.state==='failed'&&s.retryable?this.button('Retry this step',`retry-${s.id}`):''}</div></li>`).join('')||'<li>No execution has started.</li>'}</ol><p class="cl-help">${e(d.note||'Only application-reported results appear here. A request to retry is not a completed action.')}</p>${status}</section>`;}
    click(event){const action=event.target.closest('[data-action]')?.dataset.action;if(action?.startsWith('retry-')){this.emit('retry-step',{id:action.slice(6)});this.status('Step retry requested.');}}
  });
}
